import {
  Product,
  Category,
  Brand,
  ExecutiveBriefing,
  WhyRevenueChanged,
  ChartDataPoint,
  DemandSignal,
  PreOrderDemandSummary,
  InventoryHealthItem,
  DeadStockItem,
  ReorderRecommendation,
  Order,
  Coupon,
  AuditLogItem,
  UserProfile,
  SmartDealRecommendation,
} from '../types';

export const MOCK_CATEGORIES: Category[] = [
  { id: 1, name: 'Laptops & Computers', slug: 'laptops-computers', description: 'High performance productivity & gaming machines' },
  { id: 2, name: 'Wearables & Smartwatches', slug: 'wearables-smartwatches', description: 'Fitness, cellular, and premium smart devices' },
  { id: 3, name: 'Audio & Acoustics', slug: 'audio-acoustics', description: 'Studio monitors, noise-cancelling headphones' },
  { id: 4, name: 'Peripherals & Keyboards', slug: 'peripherals-keyboards', description: 'Custom mechanical boards, ergonomic mice' },
  { id: 5, name: 'Hubs & Connectivity', slug: 'hubs-connectivity', description: 'Thunderbolt docks, multi-port adapters' },
];

export const MOCK_BRANDS: Brand[] = [
  { id: 1, name: 'Lenovo' },
  { id: 2, name: 'Apple' },
  { id: 3, name: 'Bose' },
  { id: 4, name: 'Keychron' },
  { id: 5, name: 'Dell' },
  { id: 6, name: 'Sony' },
  { id: 7, name: 'Logitech' },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'Lenovo ThinkPad X1 Carbon Gen 11',
    sku: 'LAP-THINK-X1',
    description: '14-inch Ultralight Business Laptop with Intel Core i7-1365U, 32GB LPDDR5 RAM, 1TB PCIe 4.0 SSD, and 2.8K OLED Display with anti-reflective coating.',
    categoryId: 1,
    categoryName: 'Laptops & Computers',
    categorySlug: 'laptops-computers',
    brandId: 1,
    brandName: 'Lenovo',
    price: 184999.0,
    costPrice: 135000.0,
    discountPercentage: 15.0,
    finalPrice: 157249.0,
    stock: 14,
    weight: 1.12,
    dimensions: '315 x 222 x 15 mm',
    mainImageUrl: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800&auto=format&fit=crop&q=80',
    additionalImages: [
      'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=800&auto=format&fit=crop&q=80',
    ],
    rating: 4.8,
    reviewCount: 42,
    active: true,
    inventoryHealthStatus: 'HEALTHY',
    inventoryHealthScore: 92,
    salesVelocity: 2.8,
    estimatedStockoutDays: 5,
    daysSinceLastSale: 1,
    reorderPoint: 5,
    preOrderEnabled: false,
    preOrderCount: 0,
    variants: [
      { id: 1, sku: 'LAP-THINK-X1-32GB', attributesJson: '{"RAM":"32GB","Storage":"1TB SSD"}', priceOverride: 157249.0, stock: 9, active: true },
      { id: 2, sku: 'LAP-THINK-X1-64GB', attributesJson: '{"RAM":"64GB","Storage":"2TB SSD"}', priceOverride: 189999.0, stock: 5, active: true },
    ],
    specifications: [
      { specKey: 'Processor', specValue: 'Intel Core i7-1365U 10-Core' },
      { specKey: 'RAM', specValue: '32GB LPDDR5 6400MHz' },
      { specKey: 'Display', specValue: '14" 2.8K (2880x1800) OLED 400 nits' },
      { specKey: 'Battery', specValue: '57Whr (Up to 14 Hours)' },
    ],
  },
  {
    id: 2,
    name: 'Apple Watch Ultra 2 (Titanium GPS + Cellular)',
    sku: 'WEA-APPL-ULTRA2',
    description: 'Rugged titanium 49mm case with precision dual-frequency GPS, up to 36 hours normal battery life, and high-contrast 3000-nit Always-On Retina display.',
    categoryId: 2,
    categoryName: 'Wearables & Smartwatches',
    categorySlug: 'wearables-smartwatches',
    brandId: 2,
    brandName: 'Apple',
    price: 89900.0,
    costPrice: 65000.0,
    discountPercentage: 5.0,
    finalPrice: 85405.0,
    stock: 22,
    weight: 0.61,
    dimensions: '49 x 44 x 14.4 mm',
    mainImageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80',
    additionalImages: [
      'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=800&auto=format&fit=crop&q=80',
    ],
    rating: 4.9,
    reviewCount: 88,
    active: true,
    inventoryHealthStatus: 'HEALTHY',
    inventoryHealthScore: 95,
    salesVelocity: 4.1,
    estimatedStockoutDays: 6,
    daysSinceLastSale: 0,
    reorderPoint: 8,
    preOrderEnabled: false,
    preOrderCount: 0,
    variants: [
      { id: 3, sku: 'WEA-APPL-ULTRA2-ORANGE', attributesJson: '{"Band":"Ocean Band (Orange)"}', stock: 12, active: true },
      { id: 4, sku: 'WEA-APPL-ULTRA2-BLACK', attributesJson: '{"Band":"Trail Loop (Black/Gray)"}', stock: 10, active: true },
    ],
    specifications: [
      { specKey: 'Case Material', specValue: 'Aerospace-Grade Titanium' },
      { specKey: 'Water Resistance', specValue: '100m (EN13319 Certified)' },
      { specKey: 'Display', specValue: '3000 nits Always-On OLED' },
    ],
  },
  {
    id: 3,
    name: 'Bose QuietComfort Ultra Noise-Cancelling Headphones',
    sku: 'AUD-BOSE-STUDIO',
    description: 'World-class active noise cancellation with breakthrough spatialized audio and custom calibrated acoustic architecture.',
    categoryId: 3,
    categoryName: 'Audio & Acoustics',
    categorySlug: 'audio-acoustics',
    brandId: 3,
    brandName: 'Bose',
    price: 35900.0,
    costPrice: 24000.0,
    discountPercentage: 10.0,
    finalPrice: 32310.0,
    stock: 18,
    weight: 0.25,
    mainImageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80',
    additionalImages: [
      'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1545127398-14699f92334b?w=800&auto=format&fit=crop&q=80',
    ],
    rating: 4.7,
    reviewCount: 65,
    active: true,
    inventoryHealthStatus: 'HEALTHY',
    inventoryHealthScore: 88,
    salesVelocity: 3.2,
    estimatedStockoutDays: 6,
    daysSinceLastSale: 0,
    reorderPoint: 6,
    preOrderEnabled: false,
    preOrderCount: 0,
    variants: [
      { id: 5, sku: 'AUD-BOSE-STUDIO-BLK', attributesJson: '{"Color":"Triple Black"}', stock: 10, active: true },
      { id: 6, sku: 'AUD-BOSE-STUDIO-WHT', attributesJson: '{"Color":"White Smoke"}', stock: 8, active: true },
    ],
    specifications: [
      { specKey: 'Battery Life', specValue: 'Up to 24 Hours' },
      { specKey: 'ANC Mode', specValue: 'CustomTune & Immersive Audio' },
      { specKey: 'Weight', specValue: '250 grams' },
    ],
  },
  {
    id: 4,
    name: 'Keychron Q1 Pro Wireless Custom Mechanical Keyboard',
    sku: 'GAM-KEYC-Q1PRO',
    description: 'Full aluminum 75% QMK/VIA wireless mechanical keyboard with double-gasket design and hot-swappable switches.',
    categoryId: 4,
    categoryName: 'Peripherals & Keyboards',
    categorySlug: 'peripherals-keyboards',
    brandId: 4,
    brandName: 'Keychron',
    price: 18999.0,
    costPrice: 12500.0,
    discountPercentage: 0.0,
    finalPrice: 18999.0,
    stock: 0,
    weight: 1.75,
    mainImageUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop&q=80',
    additionalImages: [
      'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=800&auto=format&fit=crop&q=80',
    ],
    rating: 4.9,
    reviewCount: 31,
    active: true,
    inventoryHealthStatus: 'CRITICAL',
    inventoryHealthScore: 30,
    salesVelocity: 3.5,
    estimatedStockoutDays: 0,
    daysSinceLastSale: 2,
    reorderPoint: 10,
    preOrderEnabled: true,
    preOrderExpectedAvailability: '10 Days',
    preOrderCount: 8,
    variants: [
      { id: 7, sku: 'GAM-KEYC-Q1PRO-RED', attributesJson: '{"Switch":"Keychron K Pro Red (Linear)"}', stock: 0, active: true },
      { id: 8, sku: 'GAM-KEYC-Q1PRO-BRN', attributesJson: '{"Switch":"Keychron K Pro Brown (Tactile)"}', stock: 0, active: true },
    ],
    specifications: [
      { specKey: 'Body', specValue: 'CNC Machined Anodized Aluminum' },
      { specKey: 'Switches', specValue: 'Keychron K Pro (Hot-swappable)' },
      { specKey: 'Connectivity', specValue: 'Bluetooth 5.1 & Type-C Wired' },
    ],
  },
  {
    id: 5,
    name: 'Dell 7-in-1 Dual 4K USB-C Multiport Adapter',
    sku: 'ACC-DELL-HUB7',
    description: 'Compact 7-in-1 USB-C Hub supporting dual 4K HDMI, Gigabit Ethernet, 90W Power Delivery pass-through, and USB-A 10Gbps.',
    categoryId: 5,
    categoryName: 'Hubs & Connectivity',
    categorySlug: 'hubs-connectivity',
    brandId: 5,
    brandName: 'Dell',
    price: 7999.0,
    costPrice: 4800.0,
    discountPercentage: 12.0,
    finalPrice: 7039.0,
    stock: 6,
    weight: 0.18,
    mainImageUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80',
    additionalImages: [
      'https://images.unsplash.com/photo-1625842268584-8f3296236761?w=800&auto=format&fit=crop&q=80',
    ],
    rating: 4.6,
    reviewCount: 54,
    active: true,
    inventoryHealthStatus: 'LOW_STOCK',
    inventoryHealthScore: 45,
    salesVelocity: 2.1,
    estimatedStockoutDays: 3,
    daysSinceLastSale: 0,
    reorderPoint: 8,
    preOrderEnabled: false,
    preOrderCount: 0,
    variants: [],
    specifications: [
      { specKey: 'Ports', specValue: '2x HDMI 4K@60Hz, 2x USB-A 3.2, 1x Type-C PD, 1x RJ45, 1x SD' },
      { specKey: 'Power Delivery', specValue: 'Up to 90W Fast Pass-through' },
    ],
  },
  {
    id: 6,
    name: 'Sony WH-1000XM5 Wireless Noise-Cancelling Headphones',
    sku: 'AUD-SONY-XM5',
    description: 'Industry leading noise cancellation with two processors and 8 microphones for unmatched clarity and LDAC high-res audio.',
    categoryId: 3,
    categoryName: 'Audio & Acoustics',
    categorySlug: 'audio-acoustics',
    brandId: 6,
    brandName: 'Sony',
    price: 34990.0,
    costPrice: 23000.0,
    discountPercentage: 14.0,
    finalPrice: 30091.0,
    stock: 15,
    weight: 0.25,
    mainImageUrl: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&auto=format&fit=crop&q=80',
    additionalImages: [
      'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=800&auto=format&fit=crop&q=80',
    ],
    rating: 4.8,
    reviewCount: 92,
    active: true,
    inventoryHealthStatus: 'HEALTHY',
    inventoryHealthScore: 90,
    salesVelocity: 2.9,
    estimatedStockoutDays: 5,
    daysSinceLastSale: 0,
    reorderPoint: 5,
    preOrderEnabled: false,
    preOrderCount: 0,
    variants: [
      { id: 9, sku: 'AUD-SONY-XM5-BLK', attributesJson: '{"Color":"Black"}', stock: 9, active: true },
      { id: 10, sku: 'AUD-SONY-XM5-SLV', attributesJson: '{"Color":"Silver"}', stock: 6, active: true },
    ],
    specifications: [
      { specKey: 'Battery', specValue: '30 Hours with Quick Charge' },
      { specKey: 'Codecs', specValue: 'LDAC, AAC, SBC' },
    ],
  },
  {
    id: 7,
    name: 'Logitech MX Master 3S Wireless Performance Mouse',
    sku: 'ACC-LOGI-MX3S',
    description: 'Quiet clicks and 8K DPI track-on-glass sensor with ultra-fast MagSpeed electromagnetic scrolling wheel.',
    categoryId: 4,
    categoryName: 'Peripherals & Keyboards',
    categorySlug: 'peripherals-keyboards',
    brandId: 7,
    brandName: 'Logitech',
    price: 10995.0,
    costPrice: 6800.0,
    discountPercentage: 10.0,
    finalPrice: 9895.0,
    stock: 25,
    weight: 0.14,
    mainImageUrl: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&auto=format&fit=crop&q=80',
    additionalImages: [
      'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&auto=format&fit=crop&q=80',
    ],
    rating: 4.9,
    reviewCount: 110,
    active: true,
    inventoryHealthStatus: 'HEALTHY',
    inventoryHealthScore: 94,
    salesVelocity: 3.8,
    estimatedStockoutDays: 7,
    daysSinceLastSale: 0,
    reorderPoint: 10,
    preOrderEnabled: false,
    preOrderCount: 0,
    variants: [
      { id: 11, sku: 'ACC-LOGI-MX3S-GRY', attributesJson: '{"Color":"Space Gray"}', stock: 15, active: true },
      { id: 12, sku: 'ACC-LOGI-MX3S-WHT', attributesJson: '{"Color":"Pale Gray"}', stock: 10, active: true },
    ],
    specifications: [
      { specKey: 'Sensor', specValue: 'Darkfield 8000 DPI' },
      { specKey: 'Battery', specValue: 'Up to 70 Days per full charge' },
    ],
  },
  {
    id: 8,
    name: 'Bose QC Comfort Ear Cushion Replacement Kit',
    sku: 'ERG-BOSE-CUSHION',
    description: 'Memory foam ear cushions engineered for previous generation Bose headphones.',
    categoryId: 3,
    categoryName: 'Audio & Acoustics',
    categorySlug: 'audio-acoustics',
    brandId: 3,
    brandName: 'Bose',
    price: 3499.0,
    costPrice: 1800.0,
    discountPercentage: 0.0,
    finalPrice: 3499.0,
    stock: 40,
    weight: 0.05,
    mainImageUrl: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80',
    additionalImages: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80',
    ],
    rating: 4.2,
    reviewCount: 12,
    active: true,
    inventoryHealthStatus: 'OVERSTOCKED',
    inventoryHealthScore: 40,
    salesVelocity: 0.05,
    estimatedStockoutDays: 800,
    daysSinceLastSale: 42,
    reorderPoint: 5,
    preOrderEnabled: false,
    preOrderCount: 0,
    variants: [],
    specifications: [
      { specKey: 'Material', specValue: 'Protein Leather & Memory Foam' },
    ],
  },
];

export const MOCK_BRIEFING: ExecutiveBriefing = {
  greeting: "Good morning! Here's your enterprise operations briefing for today.",
  criticalIssues: [
    { title: 'CRITICAL Stockout Imminent', description: 'Dell 7-in-1 Hub has only 6 units left (3 days of stock remaining).', severity: 'HIGH', actionText: 'Reorder Now', actionPath: '/admin/inventory' },
    { title: 'Dead Stock Capital Tied Up', description: '₹72,000 tied up in 40 units of Bose QC Cushions with 0 sales in 42 days.', severity: 'MEDIUM', actionText: 'Create Smart Deal', actionPath: '/admin/inventory' },
    { title: 'High Risk Orders Queue', description: '2 COD orders flagged with anomaly scores >= 65 requiring review.', severity: 'HIGH', actionText: 'Review Orders', actionPath: '/admin/orders' },
  ],
  opportunities: [
    { title: 'Clustered Price Watch Demand', description: '18 users set price alerts for Bose QC Ultra at ~₹29,999. Recommended temporary promotion.', severity: 'HIGH', actionText: 'View Radar', actionPath: '/admin/demand-radar' },
    { title: 'Smart Pre-Order Commitment', description: '8 pre-orders for Keychron Q1 Pro worth ₹1,51,992. Recommended purchase order: 32 units.', severity: 'MEDIUM', actionText: 'Allocate Stock', actionPath: '/admin/preorders' },
  ],
  financialSnapshot: {
    totalRevenue: 845200.0,
    totalCOGS: 549380.0,
    totalDiscounts: 42350.0,
    totalShippingCosts: 3200.0,
    totalReturnsRefunded: 12000.0,
    estimatedProfit: 250270.0,
    profitMarginPercentage: 29.6,
    totalOrders: 16,
    averageOrderValue: 52825.0,
  },
};

export const MOCK_WHY_REVENUE: WhyRevenueChanged = {
  periodComparison: 'Prior 7-Day Period Comparison',
  overallChangePercentage: 18.4,
  topContributors: [
    { factorName: 'Laptops & Computers Surge', changePercentage: 12.5, impactType: 'POSITIVE', explanation: 'ThinkPad X1 Carbon sales grew +40% following developer promotion.' },
    { factorName: 'AOV Expansion', changePercentage: 4.8, impactType: 'POSITIVE', explanation: 'Average Order Value increased from ₹42,000 to ₹48,600 due to bundle discounts.' },
    { factorName: 'Return Rate Drop', changePercentage: 1.1, impactType: 'POSITIVE', explanation: 'Reverse logistics claims dropped from 3.2% to 1.8%.' },
  ],
  primaryRootCause: 'Developer bundle campaigns and pre-order momentum in enterprise categories.',
  aiInsightSummary: 'Strong conversion from high-value tech professionals with solid gross margins exceeding 28%.',
};

export const MOCK_SALES_TREND: ChartDataPoint[] = [
  { label: 'Aug 10', revenue: 95000, profit: 28000, orders: 4 },
  { label: 'Aug 11', revenue: 112000, profit: 34000, orders: 6 },
  { label: 'Aug 12', revenue: 88000, profit: 25000, orders: 3 },
  { label: 'Aug 13', revenue: 145000, profit: 43000, orders: 7 },
  { label: 'Aug 14', revenue: 130000, profit: 39000, orders: 5 },
  { label: 'Aug 15', revenue: 168000, profit: 51000, orders: 9 },
  { label: 'Aug 16', revenue: 195000, profit: 58000, orders: 11 },
];

export const MOCK_DEMAND_SIGNALS: DemandSignal[] = [
  {
    id: 1,
    productId: 3,
    productName: 'Bose QuietComfort Ultra Noise-Cancelling Headphones',
    productSku: 'AUD-BOSE-STUDIO',
    categoryName: 'Audio & Acoustics',
    currentPrice: 32310.0,
    currentStock: 18,
    salesVelocity: 3.2,
    searchCount: 342,
    viewCount: 1250,
    wishlistCount: 88,
    priceWatchCount: 18,
    cartAddCount: 45,
    preOrderInterestCount: 0,
    demandScore: 89,
    demandTrendPercentage: 34.5,
    status: 'HIGH',
    targetDemandPriceRange: '₹28,000 - ₹30,000',
    recommendedPrice: 29999.0,
    recommendedAction: 'Trigger 48-Hour Smart Deal at ₹29,999 to capture 18 waiting Price-Watch buyers immediately.',
    updatedAt: '2026-08-17T20:00:00',
  },
  {
    id: 2,
    productId: 1,
    productName: 'Lenovo ThinkPad X1 Carbon Gen 11',
    productSku: 'LAP-THINK-X1',
    categoryName: 'Laptops & Computers',
    currentPrice: 157249.0,
    currentStock: 14,
    salesVelocity: 2.8,
    searchCount: 510,
    viewCount: 1890,
    wishlistCount: 120,
    priceWatchCount: 24,
    cartAddCount: 62,
    preOrderInterestCount: 0,
    demandScore: 94,
    demandTrendPercentage: 18.2,
    status: 'HIGH',
    targetDemandPriceRange: '₹1,50,000 - ₹1,55,000',
    recommendedPrice: 154999.0,
    recommendedAction: 'Strong organic demand with high margins. Maintain current pricing.',
    updatedAt: '2026-08-17T20:00:00',
  },
  {
    id: 3,
    productId: 4,
    productName: 'Keychron Q1 Pro Wireless Custom Mechanical Keyboard',
    productSku: 'GAM-KEYC-Q1PRO',
    categoryName: 'Peripherals & Keyboards',
    currentPrice: 18999.0,
    currentStock: 0,
    salesVelocity: 3.5,
    searchCount: 220,
    viewCount: 890,
    wishlistCount: 45,
    priceWatchCount: 12,
    cartAddCount: 15,
    preOrderInterestCount: 8,
    demandScore: 82,
    demandTrendPercentage: 42.0,
    status: 'HIGH',
    targetDemandPriceRange: '₹18,000 - ₹19,000',
    recommendedPrice: 18999.0,
    recommendedAction: 'Out of stock! Expedite purchase order of 32 units from Keychron HK.',
    updatedAt: '2026-08-17T20:00:00',
  },
];

export const MOCK_PREORDER_SUMMARIES: PreOrderDemandSummary[] = [
  {
    productId: 4,
    productName: 'Keychron Q1 Pro Wireless Custom Mechanical Keyboard',
    sku: 'GAM-KEYC-Q1PRO',
    currentStock: 0,
    totalPreOrdersCount: 8,
    expectedRevenue: 151992.0,
    recommendedStockQuantity: 32,
    recommendedPurchaseQuantity: 32,
    expectedAvailabilityDate: '10 Days',
    supplierLeadTimeInfo: 'Standard Lead Time: 7 Days (Keychron Direct)',
  },
];

export const MOCK_INVENTORY_HEALTH: InventoryHealthItem[] = [
  { productId: 1, productName: 'Lenovo ThinkPad X1 Carbon Gen 11', sku: 'LAP-THINK-X1', currentStock: 14, salesVelocity: 2.8, estimatedStockoutDays: 5, status: 'HEALTHY', healthScore: 92, reorderPoint: 5, recommendation: 'Stock is healthy.' },
  { productId: 2, productName: 'Apple Watch Ultra 2 (Titanium GPS)', sku: 'WEA-APPL-ULTRA2', currentStock: 22, salesVelocity: 4.1, estimatedStockoutDays: 6, status: 'HEALTHY', healthScore: 95, reorderPoint: 8, recommendation: 'High velocity, maintain buffer.' },
  { productId: 4, productName: 'Keychron Q1 Pro Wireless Keyboard', sku: 'GAM-KEYC-Q1PRO', currentStock: 0, salesVelocity: 3.5, estimatedStockoutDays: 0, status: 'CRITICAL', healthScore: 30, reorderPoint: 10, recommendation: 'Out of stock! Expedite supplier shipment.' },
  { productId: 5, productName: 'Dell 7-in-1 Dual 4K USB-C Hub', sku: 'ACC-DELL-HUB7', currentStock: 6, salesVelocity: 2.1, estimatedStockoutDays: 3, status: 'LOW_STOCK', healthScore: 45, reorderPoint: 8, recommendation: 'Stockout risk within 3 days.' },
  { productId: 8, productName: 'Bose QC Comfort Ear Cushion Kit', sku: 'ERG-BOSE-CUSHION', currentStock: 40, salesVelocity: 0.05, estimatedStockoutDays: 800, status: 'OVERSTOCKED', healthScore: 40, reorderPoint: 5, recommendation: 'Tied up capital. Launch flash bundle.' },
];

export const MOCK_DEAD_STOCK: DeadStockItem[] = [
  {
    productId: 8,
    productName: 'Bose QC Comfort Ear Cushion Replacement Kit',
    sku: 'ERG-BOSE-CUSHION',
    stockQuantity: 40,
    unitPrice: 1800.0,
    deadStockValue: 72000.0,
    daysSinceLastSale: 42,
    recommendedAction: 'Create a 35% bundle discount when purchased with Bose QC Ultra headphones to clear inventory.',
  },
];

export const MOCK_REORDERS: ReorderRecommendation[] = [
  {
    productId: 5,
    productName: 'Dell 7-in-1 Dual 4K USB-C Multiport Adapter',
    sku: 'ACC-DELL-HUB7',
    currentStock: 6,
    salesVelocity: 2.1,
    predictedStockoutDays: 3,
    recommendedReorderQuantity: 25,
    suggestedSupplierName: 'Dell Enterprise Components',
  },
  {
    productId: 4,
    productName: 'Keychron Q1 Pro Wireless Custom Mechanical Keyboard',
    sku: 'GAM-KEYC-Q1PRO',
    currentStock: 0,
    salesVelocity: 3.5,
    predictedStockoutDays: 0,
    recommendedReorderQuantity: 32,
    suggestedSupplierName: 'Keychron Hong Kong Logistics',
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: 1,
    orderNumber: 'ORD-9F2B81A0',
    userId: 4,
    customerName: 'Alex Johnson',
    customerEmail: 'alex.johnson@example.com',
    phone: '+91 98765 43210',
    shippingAddress: '42 Tech Park Avenue, Indiranagar, Bengaluru, 560038',
    totalAmount: 157249.0,
    discountAmount: 0.0,
    shippingFee: 0.0,
    taxAmount: 7862.45,
    finalAmount: 165111.45,
    paymentStatus: 'SUCCESS',
    paymentMethod: 'ONLINE_CARD',
    orderStatus: 'CONFIRMED',
    riskScore: 12,
    riskLevel: 'LOW',
    riskReasons: [],
    isRiskReviewed: false,
    estimatedProfit: 22249.0,
    items: [
      { id: 1, productId: 1, productName: 'Lenovo ThinkPad X1 Carbon Gen 11', sku: 'LAP-THINK-X1', quantity: 1, unitPrice: 157249.0, totalPrice: 157249.0 },
    ],
    statusHistory: [
      { newStatus: 'PENDING', changedBy: 'CUSTOMER', timestamp: '2026-08-17T18:30:00' },
      { previousStatus: 'PENDING', newStatus: 'CONFIRMED', changedBy: 'PAYMENT_GATEWAY', timestamp: '2026-08-17T18:31:00' },
    ],
    createdAt: '2026-08-17T18:30:00',
  },
  {
    id: 2,
    orderNumber: 'ORD-7E1A4C99',
    userId: 5,
    customerName: 'Priya Sharma',
    customerEmail: 'priya.sharma@example.com',
    phone: '+91 98234 56789',
    shippingAddress: 'Flat 404, Cyber Heights, Sector 62, Noida',
    totalAmount: 85405.0,
    discountAmount: 0.0,
    shippingFee: 0.0,
    taxAmount: 4270.25,
    finalAmount: 89675.25,
    paymentStatus: 'PENDING',
    paymentMethod: 'COD',
    orderStatus: 'PENDING',
    riskScore: 68,
    riskLevel: 'HIGH',
    isRiskReviewed: false,
    riskReasons: ['High-value Cash On Delivery order (> ₹50,000)', 'Multiple failed online payment attempts before COD fallback (3 attempts)'],
    estimatedProfit: 20405.0,
    items: [
      { id: 2, productId: 2, productName: 'Apple Watch Ultra 2 (Titanium GPS)', sku: 'WEA-APPL-ULTRA2', quantity: 1, unitPrice: 85405.0, totalPrice: 85405.0 },
    ],
    createdAt: '2026-08-17T19:15:00',
  },
];

export const MOCK_COUPONS: Coupon[] = [
  { id: 1, code: 'WELCOME10', discountType: 'PERCENTAGE', discountValue: 10, minOrderAmount: 1000, maxDiscountAmount: 500, usageLimit: 1000, perUserLimit: 1, timesUsed: 84, active: true },
  { id: 2, code: 'PRODEV2000', discountType: 'FIXED', discountValue: 2000, minOrderAmount: 50000, usageLimit: 200, perUserLimit: 1, timesUsed: 37, active: true },
  { id: 3, code: 'FREESHIP', discountType: 'FIXED', discountValue: 80, minOrderAmount: 499, usageLimit: 500, perUserLimit: 1, timesUsed: 129, active: true },
];

export const MOCK_AUDIT_LOGS: AuditLogItem[] = [
  { id: 1, actor: 'admin', action: 'APPLY_PROMOTION', entityName: 'Product', entityId: '3', reason: 'Applied Smart Deal promotion at ₹29,999 to capture 18 price watch alerts', timestamp: '2026-08-17T20:00:00' },
  { id: 2, actor: 'inventory_mgr', action: 'STOCK_ADJUSTMENT', entityName: 'Product', entityId: '5', reason: 'Stock adjusted +15 units (Supplier shipment PO-901)', timestamp: '2026-08-17T19:40:00' },
  { id: 3, actor: 'order_mgr', action: 'RISK_REVIEW_APPROVE', entityName: 'Order', entityId: '1', reason: 'Verified customer phone confirmation for high value COD', timestamp: '2026-08-17T19:10:00' },
];

export const MOCK_USERS: UserProfile[] = [
  { id: 1, username: 'admin', email: 'admin@commerce.ai', fullName: 'System Administrator', enabled: true, roles: ['ROLE_ADMIN', 'ROLE_INVENTORY_MANAGER', 'ROLE_ORDER_MANAGER'], totalOrdersPlaced: 0, totalSpent: 0 },
  { id: 2, username: 'inventory_mgr', email: 'inventory@commerce.ai', fullName: 'Sarah Chen (Inventory Lead)', enabled: true, roles: ['ROLE_INVENTORY_MANAGER'], totalOrdersPlaced: 0, totalSpent: 0 },
  { id: 3, username: 'order_mgr', email: 'orders@commerce.ai', fullName: 'Marcus Vance (Fulfillment Ops)', enabled: true, roles: ['ROLE_ORDER_MANAGER'], totalOrdersPlaced: 0, totalSpent: 0 },
  { id: 4, username: 'customer1', email: 'alex.johnson@example.com', fullName: 'Alex Johnson', enabled: true, roles: ['ROLE_CUSTOMER'], totalOrdersPlaced: 3, totalSpent: 245000 },
];

export const MOCK_SMART_DEALS: SmartDealRecommendation[] = [
  {
    productId: 3,
    productName: 'Bose QuietComfort Ultra Noise-Cancelling Headphones',
    currentPrice: 32310.0,
    recommendedPrice: 29999.0,
    recommendedDiscountPercentage: 8,
    dealReason: '18 waiting price-watch buyers clustered at ₹29,999 threshold.',
    potentialImpact: 'High conversion velocity — Estimated +₹5.4L incremental revenue.'
  },
  {
    productId: 5,
    productName: 'Dell 7-in-1 Dual 4K USB-C Multiport Adapter',
    currentPrice: 7299.0,
    recommendedPrice: 6599.0,
    recommendedDiscountPercentage: 10,
    dealReason: '34 search impressions this week with high cart-add intent.',
    potentialImpact: 'Accelerates dead-stock clearance before new batch arrival.'
  }
];

